import { Metadata } from 'next'
import '@/styles/globals.scss'
import { Roboto_Flex } from 'next/font/google'
import { ThemeProvider } from '@/providers/ThemeProvider'
import Navigation from '@/components/Navigation'
import typography from '@/styles/typography.module.scss'
import { NextIntlClientProvider } from 'next-intl'
import { notFound } from 'next/navigation'

const robotoFlex = Roboto_Flex({
  subsets: ['latin'],
  variable: '--md-ref-typeface-plain',
})

export const metadata: Metadata = {
  title: 'Zydhan Linnar Putra',
  description: 'Generated by create next app',
}

export function generateStaticParams() {
  return [{ locale: 'en' }, { locale: 'id' }]
}

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode
  params: { locale: string }
}) {
  let messages
  try {
    messages = (await import(`../../messages/${locale}.json`)).default
  } catch (error) {
    notFound()
  }

  return (
    <html lang={locale} className={robotoFlex.variable}>
      <body className={typography['body-medium']}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <ThemeProvider>
            <Navigation />
            {children}
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
